services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: gridpulse-timescaledb
    restart: unless-stopped

    environment:
      POSTGRES_DB: gridpulse
      POSTGRES_USER: gridpulse
      POSTGRES_PASSWORD: gridpulse123

    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
